services:
  web:
    build: .
    command: gunicorn asman.wsgi:application --bind 0.0.0.0:8000 --workers 3
    entrypoint: ["./entrypoint.sh"] 
    volumes:
      - .:/app
      - ./static:/app/static  
      - ./media:/app/media    
      - ./.env:/app/.env    
    expose:
      - "8000"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      retries: 5


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro 
      - ./static:/app/static
      - ./media:/app/media
      - /home/elif_digitals1_gmail_com/elifgroup.store.csr:/etc/nginx/elifgroup.store.csr:ro 
      - /home/elif_digitals1_gmail_com/elifgroup.store.key:/etc/nginx//elifgroup.store.key:ro 
    
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped
    # Add this line to use your custom entrypoint
    entrypoint: ["/docker-entrypoint.sh"]






