# Generated by Django 5.2.2 on 2025-06-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title en')),
                ('description_en', models.TextField(verbose_name='Description en')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Title ru')),
                ('description_ru', models.TextField(verbose_name='Description ru')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('description_ru', models.TextField(verbose_name='Description (RU)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicetype')),
            ],
        ),
    ]
